version: "3.5"

services:
  db:
    image: postgres:12.0-alpine
    container_name: platformio_db
    env_file: 'db.env'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        APP_USER: 'user'
        SECRET_KEY: 'r84mirc+w%v)z^xbsym*+*8m5c(7%g=$z9jy_+f!27s&@0pd'
    container_name: platformio_app
    env_file: '.env'
    expose:
      - 8000
    volumes:
      - .:/app
    depends_on:
      - db
  proxy:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        CONFIG_ROOT: './docker/nginx/dev'
    container_name: platformio_proxy
    ports:
      - 9000:80
    depends_on:
      - app

volumes:
  postgres_data:
